openapi: 3.0.0
info:
  title: Bank API by Atharva
  description: API with express, nodejs, TypeScript
  version: 1.0.1
  contact:
    email: katharva2002@gmail.com
    name: Atharva
paths:
  /accounts:
    get:
      summary: Fetch account summary data
      description: Returns all data stored locally
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The account number associated with the summary data
                  name:
                    type: string
                    description: The account balance associated with the summary data
                  accType: 
                    type : string
                  email: 
                    type: string
                  date_acc_created : 
                    type : string
                  balance : 
                    type : integer
                  Nooftransaction : 
                    type : integer
  /transactions:
    get:
      summary: Fetch data of transaction
      description : shows all data with there transactions
      responses:
        "200":
          description : OK
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    description: Id of transaction
                  transactiontime: 
                    type: string
                    description : transaction time of each index 
                  amount:
                    type: integer
  /accounts/:id :
    get:
      summary : Fetch data with specific ID
      description : Output data with respected ID
      responses: 
        "200":
          description : OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    description: ID of specifc account
                  name:
                    type: string
                    description: The account balance associated with the summary data
                  accType: 
                    type : string
                  email: 
                    type: string
                  date_acc_created : 
                    type : string
                  balance : 
                    type : integer
                  Nooftransaction : 
                    type : integer
  /createAccount:
    post:
      summary : Creates account
      requestBody : 
        content : 
          application/json : 
            schema : 
              type : object 
              properties : 
                name : 
                  type : string
                  description : Name of account
                accType : 
                  type : string
                  description : Account type 
                email : 
                  type : string
                  description : Email 
                  
      responses : 
        "200" :
          description : OK
          content:
            application/json : 
              schema : 
                type : object
                properties: 
                  id : 
                    type : integer
  /accounts/getfiltertransaction/:start/end:
    get : 
      summary : Gets filtered transactions 
      description : Filtered transactions 
      responses: 
        "200":
          description : OK
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  id: 
                    type: integer
                  transactiontime:
                    type: string
                  amount: 
                    type: integer
  /accounts/delete/id : 
    delete:
      summary : deletes the specific account 
      description : deletes the specific account with parameter "id"
      responses :
        "200" : 
          description :  OK
          content :
            application/json :
              schema:
                type:  object 
                properties :
                  id: 
                    type: integer
                  name: 
                    type: string
                  accType: 
                    type: string
                  email:
                    type: string
                  data_acc_created:
                    type: string
                  balance :
                    type : integer
                  Nooftransaction:
                    type: integer
  /account/:id/deposite : 
    post : 
      summary : Deposite specific ammount in data
      description : Deposite amount to specific ID
      requestBody : 
        content : 
          application/json : 
            schema : 
              type : object 
              properties : 
                id : 
                  type : integer
                  description : Specific ID
                Amount : 
                  type : integer
                  description : amount
      responses : 
        "200" :
          description : OK
          content:
            application/json : 
              schema : 
                type : object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  accType:
                    type: string
                  email:
                    type: string
                  data_acc_created:
                    type: string
                  balance:
                    type: integer
                  Nooftransaction:
                    type: integer
  /account/:id/withdraw : 
    post : 
      summary : withdraw specific ammount in data
      description : withdraw amount to specific ID
      requestBody : 
        content : 
          application/json : 
            schema : 
              type : object 
              properties : 
                id : 
                  type : integer
                  description : Specific ID
                Amount : 
                  type : integer
                  description : amount
      responses : 
        "200" :
          description : OK
          content:
            application/json : 
              schema : 
                type : object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  accType:
                    type: string
                  email:
                    type: string
                  data_acc_created:
                    type: string
                  balance:
                    type: integer
                  Nooftransaction:
                    type: integer
